version: '3'
services:
  niceman:
    build:
      context: $PWD
      dockerfile: Dockerfile-redhat
      args:
        - IMAGE=centos:7
        - UNAME=$USER
        # - UID=1000
        # - GID=1000
    image: niceman:centos
    container_name: niceman-centos
    volumes:
      - $PWD:/home/$USER/niceman
      - /var/run/docker.sock:/var/run/docker.sock